# Generated by Django 5.2.5 on 2025-08-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
